### ISSUE TITLE
Allow users to suggest "Fields" for topics in "Rings"

### ISSUE THREAD

**Issue by fubuloubu** [ethereum-magicians/scrolls#10]
Allow suggestions of tag for specific ring (focused topic) by users.

Specifically, the following two threads are in the Working Group tag, but do not have a focused topic sub-tag (e.g. "Security Ring" here):
https://ethereum-magicians.org/t/proposed-gathering-of-the-security-community/356
https://ethereum-magicians.org/t/what-is-a-security-audit/358

P.S. the focused topic of each ring should be called a "field" because math: http://mathonline.wikidot.com/algebraic-structures-fields-rings-and-groups

**Comment by bmann** [comment]
I haven’t added an issue yet, but I’d like to turn on Discourse tag support, then people can do cross category searches / watching more easily. 

I don’t think users can do this, but OP I think has the power too. 

So — you can DM the OPs to edit & recategorize add them to the Security Ring. 

Or @jpitts will wave his admin wand ;)

**Comment by fubuloubu** [comment]
But they're not called fields... 😭
