### ISSUE TITLE
Turn on tags support in Discourse

### ISSUE THREAD

**Issue by bmann** [ethereum-magicians/scrolls#11]
This is a configuration that can be enabled, with lots of tweaks.

Here's a great blog post from the Discourse team about using tagging: https://blog.discourse.org/2017/10/its-time-we-talked-about-tags/

I think tagging EIPs in particular will be a really interesting use case, but of course it's all self organizing.

You can also set notifications per tags as well as per categories so get very fine grained updates as the forum grows.

**Comment by jpitts** [comment]
This has been enabled. We'll discuss on the Forum how to best use this.

**Comment by bmann** [comment]
Thanks Jamie!
