### ISSUE TITLE
Pls create a subtopic for Working Groups / EthSignals on forum

### ISSUE THREAD

**Issue by MaxSemenchuk** [ethereum-magicians/scrolls#12]
https://github.com/ethereum-magicians/scrolls/wiki/EthSignals-Ring

**Comment by MaxSemenchuk** [comment]
@jpitts

**Comment by jpitts** [comment]
I have created a "Signaling Ring", simplifying from EthSignals and using a form more widely used in discussions. If the ring comes to a better term, we can easily change it.

**Comment by bmann** [comment]
Thanks Jamie.
