### ISSUE TITLE
Add EIP 998 to Token Standards Ring

### ISSUE THREAD

**Issue by mudgen** [ethereum-magicians/scrolls#13]
Please add [EIP 998](https://eips.ethereum.org/EIPS/eip-998) to the list of token standards:  https://github.com/ethereum-magicians/scrolls/wiki/Token-Ring

**Comment by bmann** [comment]
@mudgen looks like you edited in, so I'm closing.

Where to put stuff -- e.g. @PhABC's comment on putting it in a repo -- totally up for discussion. We can jointly use this Scrolls repo, or you can make a shared token ring repo in this EthMagicians organization as a neutral / shared space.
