### ISSUE TITLE
Add ETH Berlin to Community Events List

### ISSUE THREAD

**Issue by aogunwole** [ethereum-magicians/scrolls#17]
title: Decoding Token Engineering Workshop
excerpt: A comprehensive workshop featuring the token experts of OST and Ocean Protocol sharing their knowledge on the best ways to design and engineer a token economy as well as optimal use cases for application. Part of the larger Berlin Blockchain Week of events.

event:
  start_date: 2018-09-06 13:00
  end_date: 2018-09-06 17:00
  location: Ocean Protocol HQ Chausseestraße 19 10115 Berlin
link: https://www.meetup.com/Token-Engineering/events/253174971/

**Comment by bmann** [comment]
Closing this here, because this is not going to be an "official" FEM project, See https://github.com/bmann/ethereum-events/issues/1
