### ISSUE TITLE
Can we make the default home page be category view?

### ISSUE THREAD

**Issue by bmann** [ethereum-magicians/scrolls#19]
As per @gcolvin discussion here: https://ethereum-magicians.org/t/choice-principles/1124/7

Is there a setting where we can make the default or non-logged-in user view be the categories page: https://ethereum-magicians.org/categories

**Comment by jpitts** [comment]
I left it in the current mode in order to increase serendipity, but it is true this is now too much. Will revert to category view shortly...

**Comment by bmann** [comment]
I like Latest, but perhaps useful for newcomers to orientate themselves. Cheers!
