### ISSUE TITLE
Revamp EthMagicians donations leaderboard

### ISSUE THREAD

**Issue by bmann** [ethereum-magicians/scrolls#22]
Our donations leaderboard is at https://donations.ethereum-magicians.org. The repo is at https://github.com/ethereum-magicians/donation-leaderboard -- it runs on Netlify.

It's a fork / branch of the Giveth leaderboard code https://github.com/Giveth/donation-leaderboard

The address goes to a multi-sig wallet that @jpitts and I currently are the two signers for.

It needs to be:
* branded and messaged as our continuous place for donations / community sponsorships
* upgraded? have features added?

One of my personal nice to haves would be to annotating transactions that aren't sent through the site. So, the ~4.x ETH, 4 of that is from Right Mesh. And the 6.7 ETH is from Santiment for ETH Berlin video / livestream.

Possible next steps:

- [ ] Look for people that want to own / drive this project
- [ ] Figure out content / messaging -- @pet3r-pan & MP, others can help with this?
- [ ] How much of a bounty would we want to stake from EthMagicians funds?
- [ ] Reach out to Gitcoin, others about possibly bounty grants or matching

**Comment by bmann** [comment]
Wrong tag @pet3r-pan

**Comment by bmann** [comment]
I believe @asselstine said that we was going to look at taking this on.

**Comment by pet3rpan** [comment]
Hello,

I am not sure who this is, but I have no idea what this is about. The
GitHub tag @pet3rpan <https://github.com/pet3rpan> was used for school work
so I think you may have the wrong person. Apologies for any inconveniences.

Cheers,
Peter

**Comment by asselstine** [comment]
@bmann I'm just having a look at it now!

**Comment by bmann** [comment]
Here is a link to @asselstine's revamp of the donations leaderboard https://zen-shirley-5f0272.netlify.com/ -- amazing, thank you!

I would say we want to remove the "offchain thanks" section completely -- that section could be more reserved for "Current Events" or similar -- it is simple enough that major sponsors and a link to the current event / donation push could be highlighted there.

@asselstine can you do a PR please? I'd love to get this much nicer version up and running. And we can file additional issues / features / content in the donations leaderboard repo.

**Comment by asselstine** [comment]
@bmann A PR has been opened here https://github.com/ethereum-magicians/donation-leaderboard/pull/2

**Comment by pet3r-pan** [comment]
Would love for someone to take lead of this project. Maybe setup a 1hr workshop for us to hash out the general comms for the leaderboard if not any other fund raising strategy.

Taking offline councils to the virtual ;)

**Comment by bmann** [comment]
Done! Thanks again @asselstine

**Comment by asselstine** [comment]
No worries @bmann :)
