### ISSUE TITLE
Is it possible for someone to move the ownership of Berlin Council

### ISSUE THREAD

**Issue by pet3r-pan** [ethereum-magicians/scrolls#23]
Is it possible for someone to move the ownership of the Berlin Council repo from the Ethereum-Magicians org into their personal profile?

It kinda bugs me that in the ethereum-magicians org that this is the only repo that is an event lol

Previous thread: https://github.com/ethereum-magicians/berlin-council/issues/6#issuecomment-424889894

**Comment by bmann** [comment]
I archived it.
