### ISSUE TITLE
Review of Brett's Discourse account

### ISSUE THREAD

**Issue by bmann** [ethereum-magicians/scrolls#26]
Hey @jpitts -- [Brett @DBrettRobertson](https://twitter.com/DBrettRobertson) has his account locked on the Discourse forum:

![image](https://user-images.githubusercontent.com/280420/47759177-aa09f680-dcae-11e8-81f9-63da00dde421.png)

He needs his account unlocked.

**Comment by DBrettRobertson** [comment]
Thank you Boris et al. the account is now unlocked. Appreciate your help.
