### ISSUE TITLE
Update Discourse version to be compatible with Mobile App

### ISSUE THREAD

**Issue by pedrouid** [ethereum-magicians/scrolls#29]
Discourse's mobile app has changed a lot in the last update (looks great, it's now called Discourse Hub) but it requires Discourse forums to update to the latest version to be compatible with the new app. I would love to continue using Ethereum Magicians on it hence this issue 😍

**Comment by pedrouid** [comment]
I know that this breaking change has happened at least on iOS but not sure if it's also true for Android because the screenshots on Play Store look outdated

iOS: https://itunes.apple.com/us/app/discourse-app/id1173672076?mt=8
Android: https://play.google.com/store/apps/details?id=com.discourse&hl=en_US

**Comment by jpitts** [comment]
DIscourse has been upgraded, try this on your iOS device now...

**Comment by pedrouid** [comment]
Perfect!! 🙌 Thanks

![img_2638](https://user-images.githubusercontent.com/10136079/48163825-94d82d80-e295-11e8-847c-0e082e9e1dec.png)
