### ISSUE TITLE
New Category "Provider Ring" for Ethereum providers

### ISSUE THREAD

**Issue by p0s** [ethereum-magicians/scrolls#31]
Please create a new Category for the Ethereum providers called "Provider Ring".

**Comment by bmann** [comment]
@p0s we need to work on a Github issue template for this, can you please add more context?

I _think_ you mean Ethereum web3 providers?

Can you also write a short "about" that will appear at the top of the forum category. Here's the Wallet Ring as an example: https://ethereum-magicians.org/t/about-the-wallet-ring-category/810

@jpitts is the one with the keys to do the actual creation.

**Comment by p0s** [comment]
@bmann You are right. It is about Ethereum web3 providers. 
Sure, I put all the information into the following forum thread: https://ethereum-magicians.org/t/forming-a-ring-provider-ring/1852

**Comment by p0s** [comment]
@jpitts could you look into creating the category?

**Comment by p0s** [comment]
Thanks for adding the category 👍
