### ISSUE TITLE
Transfer ETH to Josef for Catering Payment

### ISSUE THREAD

**Issue by bmann** [ethereum-magicians/scrolls#32]
Josef's company Polynom was the Host Organization for Prague. He arranged for catering and took in fiat funds from sponsors.

As per the [Prague budget](https://docs.google.com/spreadsheets/d/1Vm5fjJn3UnloSEQsj2ChMyowfEhOEE71ZnZWwB3VWtM/edit#gid=3), $3434.86 needs to be transferred to Josef so he can pay the remainder on the catering invoice.

**Comment by bmann** [comment]
I initiated transfer, which as of today is 16.32 ETH. @jpitts over to you to turn the other half of the key.

**Comment by pet3r-pan** [comment]
@jpitts has this been completed?

**Comment by bmann** [comment]
This has been completed, as we just had to transfer a top up because of price changes.
