### ISSUE TITLE
Feedback for Council of Prague

### ISSUE THREAD

**Issue by bmann** [ethereum-magicians/scrolls#33]
Several people

Things we might want to do:
- [ ] Email to all Council of Prague participants -- use content from wrap up post, ask for feedback, point to forum, other messages ???
- [ ] Wrap up post to the forum -- sponsor thanks, ring summary, pointer to place for followups
- [ ] Create a feedback form for structured / semi-private feedback 

For Berlin, I think we got two form submissions of structured feedback.

This is the wrap up post I wrote after Berlin: https://ethereum-magicians.org/t/council-of-berlin-wrap-up-request-for-feedback/847

Please add a comment if you're going to take one of these items and/or create a new issue and assign it to yourself.

**Comment by bmann** [comment]
I did an invite for "open" unstructured feedback https://ethereum-magicians.org/t/open-feedback-thread-for-council-of-prague/1884/, so re-worded that first checkmark item

**Comment by pet3r-pan** [comment]
@bmann I assume we can close this issue? To improve future operations - I have made a note for an issue to for an post-council protocol to do list #40

**Comment by bmann** [comment]
Well, I guess we can close it, but none of it actually got done because no one volunteered. Not sure if we just need to shill more or what. Obvs with DevCon right after everyone was totally overworked.
