### ISSUE TITLE
Decide on sponsor tiers for Council of Paris 2019

### ISSUE THREAD

**Issue by bmann** [ethereum-magicians/scrolls#45]
Typically, we have had:

* Community Tier -- a low cost tier equivalent to $1000USD worth of ETH
* Video -- $3000USD
* Food -- $3000 - $5000USD (can be smaller by splitting out coffee & lunch)
* Venue -- depends on cost

This has all been driven by costs, plus a good 30% or so buffer.

@ethernian do you have this somewhere yet? Are you taking ownership of this? I can build this into the budget #43, please let me know.

**Comment by ethernian** [comment]
Boris, 
could you suggest more sponsors and put them into [the spreadsheet](https://docs.google.com/spreadsheets/d/1LUltbNvKOL7WjNaTViDMCmrTcL8bTHR5LBZC_t7qZhI/edit#gid=0)?

**Comment by ethernian** [comment]
one more question: 
how do you deal with unspent sponsors money? 
Is it ok to have a buffer and to raise more funds or general expectation is to meet the expected expenses exactly?

**Comment by bmann** [comment]
@ethernian you can look at past sponsors from the budget sheets. I don’t have a big list anywhere. 

Yes, I recommend raising “more” than is needed — cost plus a buffer. Once I have the budget filled out we’ll know what we need. 

We have the ETH in the donations wallet that includes previous funds we can use.

**Comment by tomislavmamic** [comment]
This is in progress. Due date this Friday. 
Can I get the access for managing the backlog?
