### ISSUE TITLE
Reach out to Ring contacts

### ISSUE THREAD

**Issue by jpitts** [ethereum-magicians/scrolls#47]
- Ping the Ring contacts and regulars, take note of where each Ring is. 
- Find out about participation in EthDenver and EthCC
- Find out what they generally need to happen over the next few months
- Let them know we will be organizing pick-up tasks, will ping them again to add some

**Comment by pet3r-pan** [comment]
This might help https://docs.google.com/spreadsheets/d/1Wg_eX-mYopvWT3LeHe4-FEHOtJoG28h8YcHl4PFTX5k/edit#gid=0
