### ISSUE TITLE
Create two new ring categories on FEM forum

### ISSUE THREAD

**Issue by pmauric** [ethereum-magicians/scrolls#49]
"Fund Recovery Ring" and "Multisig Ring" 

Thanks!

**Comment by jpitts** [comment]
Sorry the run-up to the holidays distracted me from monitoring the issues, I should be able to get to it tomorrow.

**Comment by jpitts** [comment]
@pmauric I have created these. Are you to be the contact? I can participate in the Multisig Ring also if you need an additional contact. Both of these need Ring charters in the Scrolls.
