### ISSUE TITLE
Create new category under "Fellowship Gatherings"

### ISSUE THREAD

**Issue by pmauric** [ethereum-magicians/scrolls#50]
Hackathons - there has been interest in doing some governance signaling hackathon from both the team that emerged from the Council of Berlin and others. Figured it's a different sorta gathering to tackle so it deserves its own category. 

Thanks

**Comment by jpitts** [comment]
Sorry the run-up to the holidays distracted me from monitoring the issues, I should be able to get to it tomorrow.

**Comment by pmauric** [comment]
Cool thanks!

**Comment by jpitts** [comment]
@pmauric, this is in place. Sorry it took so long, I overlooked this.
