### ISSUE TITLE
Create a new category in the forum for the Mobile Ring

### ISSUE THREAD

**Issue by pcowgill** [ethereum-magicians/scrolls#52]
Hi, can you please create a new category in the forum for the new Mobile Ring? Thanks!

https://ethereum-magicians.org/t/forming-a-ring-mobile-ring/2358

https://github.com/ethereum-magicians/scrolls/wiki/Mobile-Ring

**Comment by ltfschoen** [comment]
@pcowgill propose to close this issue as a new category appears to have been created https://ethereum-magicians.org/c/working-groups/mobile-ring

**Comment by pcowgill** [comment]
@ltfschoen Thanks for pointing this out! Done.
