### ISSUE TITLE
Volunteer sought: Manage DAI for Council of Paris ETH ticket payments & EthMagicians wallet

### ISSUE THREAD

**Issue by bmann** [ethereum-magicians/scrolls#55]
We are using Pretix for #53 ticketing solution for Council of Paris. Instructions indicate to send ETH to the EthMagicians wallet*.

We also have the previous ECF donation for this event currently sitting in ETH.

I am suggesting that we transfer some ETH into DAI for the tickets as payments come in, and for the lump sum of the ECF sponsorship.

I am also asking for a volunteer to join @jpitts and I in managing the EthMagicians wallet.

So, specifically:
* looking for a volunteer to be a third member of the wallet, with 2-of-3 permissions
* looking for that same volunteer to manage DAI -- creating a CDP or however this works :)
* in the lead up to Council of Paris 2019, regularly turn ETH into DAI as ticket payments come in

If you are new to the community, please make sure you have signed up in the forums at https://ethereum-magicians.org

_*Also: we COULD request that people send DAI to the address as well, which just means updating the instructions._

**Comment by ligi** [comment]
I do not think we need to/should create a CDP - we can just exchange ETH->DAI - e.g. on https://oasis.direct

if no-one else steps up I could fill the role searched here - but would also be *very* happy if someone else is doing it as I hate dealing with significant funds.

**Comment by meknab-zz** [comment]
Hi, I would be happy to help. I am the founder of a crypto accounting startup (http://www.veriledger.io )  and have experience managing crypto treasuries for companies I have worked at in the past. Happy to provide further background info and chat further.

**Comment by Flash-Git** [comment]
Just caught up on the magicians' discussion, I've played around with maker's CDP and currently have a couple. I'd love to help!

**Comment by ligi** [comment]
great we have some volunteers now that want to help! But we should really discuss if we need CDPs. IMHO we should not do this and just exchange ETH->DAI
What advantages do you see in using a CDP instead of just exchanging?

**Comment by bmann** [comment]
@ligi I can't find the thread, but Aidan @chainsafe was suggesting it would be "Easy to setup a CDP", around when #24 came up. 

I put "creating a CDP or however this works" -- because I don't know enough to make this decision and want the volunteer to have some expertise/experience and advise us.

There's a whole bunch of "treasury management" going forward, too. Scope for now is as listed in this issue -- I would propose we get agreement on other things in separate issues.

For now -- "convert ETH to DAI held in the EthMagicians wallet" is fine. At the end of the process, someone will need to make a fiat payment to caterers (for example) and will need to accept DAI to cover expenses.

Does that make sense?

**Comment by ChainSafeSystems** [comment]
@ligi I would be happy to help out with whatever DAI related, I totally agree that it makes most sense to just trade ETH -> DAI. 

> For now -- "convert ETH to DAI held in the EthMagicians wallet" is fine. At the end of the process, someone will need to make a fiat payment to caterers (for example) and will need to accept DAI to cover expenses.

@bmann not sure if I can help on the fiat side of things, but I can help with the crypto.

**Comment by bmann** [comment]
@chainsafe see the [discussion on EthMagicians](https://ethereum-magicians.org/t/stable-magicians-poll-exchange-vs-cdp/2377) for the context.

Let's keep this thread focused on identifying a volunteer, please.

@Flash-Git I DM'd you in the forum -- thanks! For reference, @Flash-Git reserved ethmagicians.eth as an ENS name, see #21 

@meknab thanks so much for posting here and DM'ing on Twitter. I think we probably need someone with more community exposure BUT we'd love to get some advice / lean on your expertise? Maybe we could ask for a call about treasury management tips?

**Comment by meknab-zz** [comment]
Sure, happy to contribute however works best. IMO, CDPs would be an extra level of complication that is unnecessary, but worth understanding better what is required of the treasury.

**Comment by meknab-zz** [comment]
Also, just to throw out there, I have some crypto-friendly US banking relationships that might be of benefit if needed.

**Comment by bneiluj** [comment]
@bmann what's the current status of those points ? 

1. looking for a volunteer to be a third member of the wallet, with 2-of-3 permissions
2. looking for that same volunteer to manage DAI -- creating a CDP or however this works :)
3. in the lead up to Council of Paris 2019, regularly turn ETH into DAI as ticket payments come in

I can help on the DAI - ETH - CDP.

**Comment by ligi** [comment]
> I can help on the DAI - ETH - CDP.

the signaling is strong to not do a CDP - just to exchange ETH->DAI on an exchange

poll here: https://ethereum-magicians.org/t/stable-magicians-poll-exchange-vs-cdp/2377

**Comment by nanexcool** [comment]
Hi! I'd like to volunteer to help handle the ETH -> DAI exchange. I work at Maker and am trying to be very vocal in all communities and helping out whenever I can, and EthMagicians is just about the greatest ever :)

I agree that exchanging ETH into Dai is the sane idea, opening a CDP while not a big deal, implies speculating with ticket money. You want fairly fast conversions from ETH to Dai to protect against volatility, and/or you can also request straight up payments in Dai. There are events that already do this. Avado sells their DAppNode for Dai. And we can eventually figure out off-ramps to fiat if needed.

Let me know if this is something I can help!

**Comment by ethernian** [comment]
I am quite familiar with ETH/CDP/DAI and ready to help if there any need.

As already mentioned, there is no direct need to open CDP in order to become DAI. [Just trade on oasis.direct](https://oasis.direct).
The only reasons I see to create CDP are:
1. speculating on rising ETH in the future. Use DAI now, sell ETH later.
2. support Maker system by creating additional DAI liquidity.
3. trading ETH-DAI may be a taxation event. Borrowing DAI from CDP and hodling ETH in  CDP is most probably not (and preserves your 1 year tax free time frame). 

All of that reasons are not directly related to the event. So we should trade, not open CDP.
But if we have unspent remainder at the end of the event, may be it will make sense put into CDP.

**Comment by jpitts** [comment]
Great to hear we have volunteers! It will be a learning experience and we can make the procedures & documentation available to the community.

RE: ideas about the process for converting ETH to DAI, I have created a HackMD. Please post your proposals there (as complete as possible) and we all can review them later: https://hackmd.io/s/H1ZWRSrz4

**Comment by ligi** [comment]
@jpitts from your proposal:

> DEXs will probably require using a single key interact with the DEX as opposed to a multisig.

I am pretty sure you can use a DEX with a multisig. That said I have never done that yet. Perhaps @nanexcool has some input on osasis compatibility with multisigs

**Comment by nanexcool** [comment]
@ligi multisig or single address makes no difference to Oasis. But, the speed at which you send transactions might. There's two ways to interact with Oasis:
 - Execute an order that's already there, say someone is selling 100 Dai for X ETH
 - You submit an order, "I want to buy X amount of ETH, here's 100 Dai"
Since multisig txs usually take longer because you need N signatures to confirm, once you do confirm the order may have already been filled. Or you may want to cancel an order if the price has shifted too much.
Anyway, point is it is totally possible to use a multisig.

**Comment by bmann** [comment]
I'm going to close this for now. @Flash-Git I'll PM you in the forum about getting on a call with me and @jpitts.

And we've got @meknab scheduled for a treasury management session. I'm going to call this a success! Thanks everyone!
