### ISSUE TITLE
Sponsor text for Council of Paris 2019

### ISSUE THREAD

**Issue by bmann** [ethereum-magicians/scrolls#57]
Moved from #46 via @ethernian -- also, I've made you a collaborator on the repo so you can help manage issues.

I've pasted in the text, but more useful for editing collaboratively via HackMD -- https://hackmd.io/dO0BZxjNTK6FjSDHuWDs1w

---

Ethereum Magicians Council is a regular gathering of Ethereum Community focused on current progress and challenges in Ethereum community and technology. In contrast to usual conferences and meetups where preselected speakers presenting their work to broader audience, Magicians Councils are organized around working groups called Rings open for anyone to participate. The goal of the Council is to facilitate communication in the community across usual circles. It gives anyone a chance to be heard, to understand concerns of others, to find colleagues to work together on some topic or start a new one.

Because of great inclusivity of the Council and its unique format, the number of participants have arose quickly. Starting from XX people in Berlin in June 2018, we counted almost YY people in Prague in Nov 2018. Although volunteers become no money, it becomes challenging to organize the event for such amount of people and cover all the costs. That is why we need your help.

We appreciate our sponsors very much and would like to offer various perks as a part of our sponsorship packages. In particular we are offering logo and poster placements in our video recording and in venue which becomes visible not only for hunderts of participants during the event, but also online for broader public for a long time hereafter.

Please see our sponsorship packages here. We would be pleased to welcome you as our sponsor.

**Comment by bmann** [comment]
The Prague sponsorship deck is here --> https://drive.google.com/open?id=1r96uMz_jCe6wDvXdfkhy4QHl-APdoASDwURJIcMBdOs

I have edited the text in HackMD https://hackmd.io/dO0BZxjNTK6FjSDHuWDs1w

I'm not sure where this text should go? Past events didn't have this anywhere on the landing page, other than updates that were "Calls for sponsors".

**Comment by tomislavmamic** [comment]
Added the (shorter version) of sponsor text to the website.
