### ISSUE TITLE
Add MP and Tomislav to Tweetdeck access for ETHMagicians

### ISSUE THREAD

**Issue by mariapaulafn** [ethereum-magicians/scrolls#60]
Link here: https://ethereum-magicians.org/t/council-of-paris-call-for-rings-and-participants/2588

**Comment by bmann** [comment]
Thanks @mariapaulafn -- I meant Github Issues for adding you as a Tweeter access. I have tweeted and will promote / RT on my personal account as well.

@jpitts can you please add @mariapaulafn and @tomislavmamic to Tweetdeck access for the EthMagicians Twitter account so they can help get the word out.

**Comment by jpitts** [comment]
Ok, you both have been added. Let me know if it works.

**Comment by mariapaulafn** [comment]
Hi! i only use browser for @ethberlin so if you can add that one, great

**Comment by bmann** [comment]
I'll close this issue, assuming @jpitts added EthBerlin as well.
