### ISSUE TITLE
Tweet call for DAO ring

### ISSUE THREAD

**Issue by mariapaulafn** [ethereum-magicians/scrolls#61]
A new topic's been proposed for @ethmagicians, yes, it's DAOs! 
join @stellarmagnet, @mptherealmvp and others discussing the year of the DAO https://hackmd.io/s/ByIVnZVdX

**Comment by bmann** [comment]
@mariapaulafn you should have access via Tweetdeck to EthMagicians account now. 

If this is a general call to help promote DAO as a topic - cool ;)

**Comment by mariapaulafn** [comment]
@bmann yes it is - i just left a note that i dont use my personal tw on browser because of the accounts i manage, if its fine please either add @ethberlin or maybe @tomislavmamic can also pick up my issues to tweet here

**Comment by bmann** [comment]
I believe this got done. And I just tweeted it from my personal account :)
