### ISSUE TITLE
New Ring: VM Ring

### ISSUE THREAD

**Issue by bmann** [ethereum-magicians/scrolls#62]
Please create a "VM Ring".

Purpose: to discuss EVM and eWASM design, improvements, and compatibility. New opcode definition. Keeping Jello / Yellow paper specifications up to date.

cc @gcolvin @expede

**Comment by ltfschoen** [comment]
Created ring on Discourse: https://ethereum-magicians.org/t/forming-a-ring-vm-ring/2830
