### ISSUE TITLE
Make a forum category called “Core Devs” or “Core EIPs”

### ISSUE THREAD

**Issue by bmann** [ethereum-magicians/scrolls#63]
James Prestwich has suggested that a category name that would be more inclusive is Core Devs. I might also suggest Core EIPs, since we already have an “EIPs” category. 

https://twitter.com/_prestwich/status/1109915114222702592

**Comment by jpitts** [comment]
This is interesting, this could be a sub-category of EIPs. Should I create categories for all of the types of EIPs?

**Comment by jpitts** [comment]
This is added, if we end up adding all of the types then we may consider changing the parent category "EIPs" to "Proposals".

**Comment by bmann** [comment]
Possibly!

Having a curated Core EIPs should mean for now that people can follow only it and know that it will be highly relevant.

Let's see how this goes...
