### ISSUE TITLE
Create a Core Devs Meeting Notes category

### ISSUE THREAD

**Issue by bmann** [ethereum-magicians/scrolls#66]
The first Core Dev Meeting Notes were published https://ethereum-magicians.org/t/ethereum-core-devs-meeting-58-summary/3053

The suggestion is to make a category so all of these can easily be tracked and subscribed to. 

A couple of suggestions:
- Put it under the EIPs category as EIPS > Core Dev Meeting Notes
- Put it under Action Items > Core Dev Meeting Notes
- Put it under Fellowship Gatherings > Core Dev Meeting Notes

Looking ahead, where we might host Core Dev “mailing list”, it could also go under a new top level category called Core Devs, and then Core Devs > Meeting Notes

The goal is to make them easy to see and act on and have long form discussion about, in a place that is less buried than GitHub issues. 

Whoever is compiling the notes may also post them to the Ethereum/PM repo as Markdown files, but that is up to those volunteers to determine.

**Comment by jpitts** [comment]
Ok I created this category, a new topic can be placed there for each instance where notes or other content are being created. https://ethereum-magicians.org/c/fellowship-gatherings/core-devs-meeting-notes
