### ISSUE TITLE
Pay Asseth for ETHCC from EthMagicians wallet

### ISSUE THREAD

**Issue by bmann** [ethereum-magicians/scrolls#67]
The final totals are in from EthCC. We have paid out fiat sponsorships from Open Collective - https://opencollective.com/ethmagicians-eu/events/council-of-paris-2019-27245ev

Now we need to pay Asseth the remaining 3304.20EU

Waiting on an address from them, then we can process this.

**Comment by bmann** [comment]
Asseth's address is `0xD8FF82D36D1439eD3eF8cBb4b28178Ff7F6b7209`.

From CoinGecko, today's EUR to ETH rate is €149.79, so 22.0589 ETH

@jpitts I'm starting one half of this transaction, please approve it when you see it.

**Comment by jpitts** [comment]
This has now been confirmed:

https://etherscan.io/tx/0x789df5f6f735eafac985aa3f164467beeab600fe31b15b2f18f820add85b402f

**Comment by bmann** [comment]
Thanks @jpitts — marking as closed.
