### ISSUE TITLE
Extending the multisig owners and operations ring

### ISSUE THREAD

**Issue by bmann** [ethereum-magicians/scrolls#68]
After discussing with @jpitts, we are adding Megan and James to the EthMagicians multisig and operations ring.

Right now the multisig is just Jamie and @bmann, and Boris (me!) doesn’t want to be 50% responsible for handling operations related to the wallet.

Megan has experience with crypto accounting and had previously volunteered to help out more.

James has been an active participant and previously volunteered.

Likely we will set it up as 2 of 4. We can also potentially, using [Multis](https://multis.co) features, give allowances to non multisig holders, but we haven’t needed this capability yet.

This issue is to track the process of completing the move to 2 of 4.

**Comment by timbeiko** [comment]
Is the address of the multisig public?

**Comment by Flash-Git** [comment]
Thanks Boris! @timbeiko the address can be found at https://etherscan.io/address/ethmagicians.eth

**Comment by bmann** [comment]
@timbeiko also at https://donations.ethereum-magicians.org.

**Comment by bmann** [comment]
I have invited @Flash-Git and Megan via email to Multis — please create an account and link the address of the wallet you’ll use.

**Comment by bmann** [comment]
@Flash-Git has linked his address into Multis and I have submitted him as an owner. 

@jpitts you need to approve this on chain.

**Comment by bmann** [comment]
Megan has linked her address to Multis, and I have entered the request to add her as an owner. @jpitts you need to approve.

**Comment by jpitts** [comment]
Sorry about the delay, I'll approve shortly!

**Comment by jpitts** [comment]
Ok these approvals have been submitted:

https://etherscan.io/tx/0xd71bb20dc737bcb14ad7fef0c8ec83171f46ba1ccae26157470dd136bfb148a5

https://etherscan.io/tx/0xa7efeb667fda0edf3edaf642b9a2d4717442986a499976da42dc32e24d30731f

**Comment by bmann** [comment]
Completed! Thanks Jamie!
