### ISSUE TITLE
Create YouTube shorts for each video uploaded to View.ly

### ISSUE THREAD

**Issue by bmann** [ethereum-magicians/scrolls#7]
This way we'll have entry points near most of the Ethereum-related videos.

**Comment by tomislavmamic** [comment]
Guys, can you please tell me more about this idea? Maybe we at Viewly can engage our creators to do these short videos? What would be their purpose?

**Comment by bmann** [comment]
This was @jpitts idea about the full length videos from Berlin from the livestream. 

Taking the full videos and editing into some shorter clips, especially comments from individual people.

**Comment by pet3r-pan** [comment]
@bmann Do you think we still need this? If so, at the least we should upload these videos also onto youtube as a backup. I can't download the view.ly videos + the dropbox link of raw footage is broken.

Proper archiving of councils are really important imo and should have a efficient protocol behind them.

**Comment by bmann** [comment]
Yes the Dropbox is gone. I believe @jpitts has a backup of the originals, I do as well. 

Can close this.

**Comment by tomislavmamic** [comment]
I believe I have the back up files as well
