### ISSUE TITLE
Investigate Open Collective for use in tracking expenses, taking fiat payment

### ISSUE THREAD

**Issue by bmann** [ethereum-magicians/scrolls#8]
I am going to investigate using Open Collective https://opencollective.com so we can transparently track expenses, potentially use it accept fiat, and see what else it is useful for.

**Comment by bmann** [comment]
OK, I've got something basic setup, and have invited @jpitts in as a Core Contributor. See https://opencollective.com/ethmagicians/

It supports events (yay!) but the ticket / registration is pretty basic. I would use it mainly for collecting fiat sponsorships and re-imbursing expenses.

See https://opencollective.com/ethmagicians/events/council-of-prague-18470ev for me putting in a Prague event. Again, just for fiat donations & sponsorships.

One issue is that expenses and sponsorships go into the Open Collect non profit, who in turn re-imburses, I think mainly via PayPal? So, re-imbursing someone with ETH may not work. We can experiment with me and see if it works.

Maybe somebody converts ETH and then donates it so it can be fiat re-imbursed? Seems complicated.

OpenCollective itself is open source - https://github.com/opencollective/opencollective (that's the management repo, the other repos have API, frontend, etc.).

**Comment by ligi** [comment]
For tickets you might want to look into: https://pretix.eu/about/de - we could even do some blockchain experiments on top of this.
That said: this issue feels a bit miss-placed in "scrolls"

**Comment by bmann** [comment]
I'm going to look more at this along with #44 

Specifically, this is likely the best way to be transparent around costs and sponsorships. Can experiment with @jpitts submitting (e.g.) hosting expenses to this existing org.

**Comment by bmann** [comment]
OK, I'm closing this now. After talking to the founder and investigating this further, this CAN work for us instead of Host Organizations.

There are two collectives partially set up:
* US edition: https://opencollective.com/ethmagicians/ 
* EU edition: https://opencollective.com/ethmagicians-eu/
